from setuptools import setup, find_packages

setup(
    name="crypto_volatility",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "streamlit==1.31.1",
        "pandas==2.1.4",
        "numpy==1.24.3",
        "yfinance==0.2.36",
        "scikit-learn==1.3.2",
        "tensorflow==2.15.0",
        "plotly==5.18.0",
        "hmmlearn==0.3.0",
        "dtw-python==1.3.0",
        "joblib==1.3.2",
        "pytest==7.4.3",
        "websockets==12.0",
        "python-json-logger==2.0.7",
        "prometheus-client==0.19.0",
    ],
    extras_require={
        'dev': [
            'black==24.1.1',
            'flake8==7.0.0',
            'mypy==1.8.0',
            'isort==5.13.2',
            'pytest-cov==4.1.0',
            'pytest-mock==3.12.0',
            'sphinx==7.2.6',
            'sphinx-rtd-theme==2.0.0',
        ],
    },
    python_requires=">=3.8",
    author="Your Name",
    author_email="your.email@example.com",
    description="Cryptocurrency volatility analysis and prediction",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/crypto_volatility",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Financial and Insurance Industry",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
)