[server]
# If false, will attempt to open a browser window on start.
headless = true

[browser]
# Internet address where users should point their browsers in order to connect to the app.
serverAddress = "0.0.0.0"

[runner]
# The command line command to run the Streamlit app
command = "python -m streamlit run src/dashboard.py"

[logger]
level = "info"

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
# Whether to enable st.cache.
caching = true

[global]
developmentMode = false 