[server]
# If false, will attempt to open a browser window on start.
headless = true

[browser]
# Internet address where users should point their browsers in order to connect to the app.
serverAddress = "0.0.0.0"

[logger]
level = "info"

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[global]
developmentMode = false 